#!/usr/bin/env bash

set -euo pipefail

goto_repo_root() {
    local root
    root=$(git rev-parse --show-toplevel)
    if [ $? -eq 0 ]; then
        echo "Building KEVM at $root"
        cd "$root" || return
    else
        echo "You're not inside a Git repository."
    fi
}

LLVM_DEBUG=""
for arg in "$@"
do
    if [ "$arg" == "--with-llvm-debug" ]; then
        LLVM_DEBUG="--arg enable-llvm-debug=true"
        break
    fi
done

goto_repo_root

git submodule update --init --recursive --depth 1 kevm-pyk/src/kevm_pyk/kproj/plugin

kup install k.openssl.procps.secp256k1 --version v$(cat deps/k_release)

make poetry

poetry -C kevm-pyk run kdist clean

CXX=clang++-14 poetry -C kevm-pyk run kdist --verbose build evm-semantics.plugin -j`nproc`

poetry -C kevm-pyk run kdist --verbose build -j4 $LLVM_DEBUG
