#!/usr/bin/env bash

set -euo pipefail

UPDATE_OUTPUT=false
for arg in "$@"
do
    if [ "$arg" == "--update-output" ]; then
        UPDATE_OUTPUT=true
        break
    fi
done

cd $KONTROL

kup install k.openssl.procps --version v$(cat deps/k_release)

poetry install

poetry run kdist clean

CXX=clang++-14 poetry run kdist --verbose build -j2 evm-semantics.haskell kontrol.foundry

# Update expected output if flag is passed
if [ "$UPDATE_OUTPUT" = true ]; then
    make cov-integration TEST_ARGS="--numprocesses=8 --update-expected-output"
fi
