#!/usr/bin/env bash

set -euo pipefail

goto_repo_root() {
    local root
    root=$(git rev-parse --show-toplevel)
    if [ $? -eq 0 ]; then
        echo "Building KONTROL at $root"
        cd "$root" || return
    else
        echo "You're not inside a Git repository."
    fi
}

install_k() {
    echo "Installing or updating K to version $REQUIRED_VERSION..."
    kup install k.openssl.secp256k1 --version "$REQUIRED_VERSION"
}

UPDATE_OUTPUT=false
for arg in "$@"
do
    if [ "$arg" == "--update-output" ]; then
        UPDATE_OUTPUT=true
        break
    fi
done

goto_repo_root

REQUIRED_VERSION=v$(cat deps/k_release)

# Check if K is installed and get the current version
if command -v kompile &> /dev/null; then
    INSTALLED_VERSION=$(kompile --version | grep "K version:" | awk '{print $3}')
    echo "Installed version: $INSTALLED_VERSION"

    # Compare installed version with required version
    if [[ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]]; then
        echo "K version is outdated. Updating..."
        install_k
    else
        echo "K version is up to date."
    fi
else
    echo "K is not installed. Installing..."
    install_k
fi

poetry install

poetry run kdist clean

CXX=clang++-14 poetry run --no-cache kdist --verbose build -j8 evm-semantics.haskell kontrol.foundry

# Update expected output if flag is passed
if [ "$UPDATE_OUTPUT" = true ]; then
    make cov-integration TEST_ARGS='--numprocesses=6 --maxfail=100 --update-expected-output -vv -k "not (test_kontrol_cse or test_foundry_minimize_proof or test_kontrol_end_to_end)"' | tee running-tests.log
    make cov-integration TEST_ARGS='--numprocesses=4 --maxfail=100 --update-expected-output -vv -k "test_kontrol_cse or test_foundry_minimize_proof"' | tee running-cse-tests.log
fi
