#!/usr/bin/env bash

set -euo pipefail

goto_repo_root() {
    local root
    root=$(git rev-parse --show-toplevel)
    if [ $? -eq 0 ]; then
        echo "Building KONTROL at $root"
        cd "$root" || return
    else
        echo "You're not inside a Git repository."
    fi
}

UPDATE_OUTPUT=false
for arg in "$@"
do
    if [ "$arg" == "--update-output" ]; then
        UPDATE_OUTPUT=true
        break
    fi
done

goto_repo_root

kup install k.openssl.procps --version v$(cat deps/k_release)

poetry install

poetry run kdist clean

CXX=clang++-14 poetry run --no-cache kdist --verbose build -j2 evm-semantics.haskell kontrol.foundry

# Update expected output if flag is passed
if [ "$UPDATE_OUTPUT" = true ]; then
    make cov-integration TEST_ARGS="--numprocesses=11 --update-expected-output"
fi
